alibaba/serverless-vscode

- README.md
- package.json
vscode extension 打包需要 README 中的所有的图片 src 都是 https
> docs: change image url

- README.md
- src/commands/localDebugFunction.ts
- src/services/FunService.ts
- src/utils/runtime.ts
修复初次 pull image 时，由于 container 还未启动，vscode debugger 无法 attach 到目标，提示系统错误。
提供多 debug port 支持，支持多 debug session 调试。
re #4, #7
> perf(Local Debug): 提升初次调试体验以及支持多 Session 调试

- package-lock.json
- package.json
- src/commands/bindAccount.ts
- src/commands/showRegionStatus.ts
- src/commands/switchAccount.ts
- src/commands/switchOrBindAccount.ts
- src/commands/switchRegion.ts
- src/commands/switchRegionOrAccount.ts
- src/extension.ts
- src/ui/MultiStepInput.ts
- src/utils/config.ts
support save multi account info and switch to any account
re #9
> feat(multi account): support save multi account info and switch

- package.json
> perf(Extension Active): extension active when found template.yml

- src/definitions/ServerlessDefinitionProvider.ts
- src/extension.ts
- src/utils/runtime.ts
re #20
提供 template.yml 中针对函数 Handler 定义的跳转
> feat(Template Link): show function definition link in template.yml

- package-lock.json
- package.json
- src/completions/ServerlessCompletionProvider.ts
- src/extension.ts
- src/parser/ASTNode.ts
- src/parser/ArrayASTNode.ts
- src/parser/BooleanASTNode.ts
- src/parser/ItemASTNode.ts
- src/parser/NullASTNode.ts
- src/parser/NumberASTNode.ts
- src/parser/ObjectASTNode.ts
- src/parser/PropertyASTNode.ts
- src/parser/SlotASTNode.ts
- src/parser/StringASTNode.ts
- src/parser/parser.ts
- src/schema/constants.ts
- src/schema/schema.ts
- src/utils/constants.ts
- src/utils/document.ts
1. 提供更加精确的 key 字段提示
2. 去除原先的 Snippet，但是 Snippet 效果仍然存在，详情见图
3. 提供每个资源的文档链接地址
re #21
> feat(Template AutoCompletion): 提供 key 字段的精确提示

- src/lens/ServerlessLensProvider.ts
> fix(CodeLen): 修复 CodeLen 在视窗外时输入内容滚动条抖动

- src/commands/showUpdateNotification.ts
- src/extension.ts
- src/utils/constants.ts
> feat(Update Notification): 新增版本更新通知

- package.json
- src/commands/reportIssue.ts
- src/commands/viewDocumentation.ts
- src/commands/viewQuickStart.ts
- src/commands/viewSource.ts
- src/extension.ts
- src/utils/constants.ts
> perf(Local Resource Menu): 提供更多菜单项

- resources/web/service/index.html
> perf(Service Webview): 服务没有 NAS 配置时，不展现挂载表格

- src/diagnostics/ServerlessDiagnosticsProvider.ts
- src/extension.ts
- src/language-service/jsonSchema.ts
- src/language-service/parser/jsonParser.ts
- src/language-service/schema/funSchema.json
- src/language-service/services/jsonSchemaService.ts
- src/parser/ASTNode.ts
- src/parser/ArrayASTNode.ts
- src/parser/NumberASTNode.ts
- src/parser/ObjectASTNode.ts
- src/parser/PropertyASTNode.ts
- src/utils/document.ts
#26
template.yml 提供 Service 以及 Function Schema 校验
> feat(Template Validation): template.yml 提供 Service 以及 Function Schema 校验

- src/commands/gotoFunctionTemplate.ts
- src/commands/gotoServiceTemplate.ts
- src/definitions/ServerlessDefinitionProvider.ts
- src/utils/document.ts
> feat(Template Jump): 跳转到服务或函数的 yaml 定义时，提供色块显示

- src/language-service/schema/funSchema.json
- src/schema/constants.ts
- src/schema/schema.ts
> perf(Template Schema): 补充关于资源的 Schema 定义以及 Snippet 文本

- package.json
- src/commands/deployFunction.ts
- src/commands/deployService.ts
- src/extension.ts
- src/services/FunService.ts
- src/utils/constants.ts
re #61
支持局部部署服务函数，在 Local Resource 面板中右键相关资源选择 Deploy Service 或 Deploy Function 即可局部部署
> feat(Partial Deploy): 支持局部部署服务函数

- src/commands/gotoFunctionTemplate.ts
- src/commands/gotoServiceTemplate.ts
- src/commands/gotoTriggerTemplate.ts
- src/decorations/RainbowDecorator.ts
- src/extension.ts
- src/utils/document.ts
re #56
为 template 文件提供 tab/space(space 大小根据用户设定的 tabSize 决定) 的 rainbow 渲染
> feat(Template Rainbow): template 文件提供 rainbow 渲染

- src/commands/createFunction.ts
- src/commands/localDebugFunction.ts
- src/language-service/schema/funSchema.json
- src/utils/runtime.ts
- templates/nodejs-http/index.js
- templates/php-http/index.php
> feat(Nodejs10 Runtime): 支持 Nodejs10

- src/completions/ServerlessCompletionProvider.ts
- src/diagnostics/ServerlessDiagnosticsProvider.ts
- src/schema/constants.ts
- src/schema/schema.ts
- src/services/TemplateService.ts
- src/utils/constants.ts
- src/utils/document.ts
> perf(Template Completion And Validation): 空模版文件快速构建以及优化 Validation 触发方式

- src/commands/remoteInvokeFunction.ts
- src/services/FunctionComputeService.ts
> perf(Remote HTTP Trigger): 调用远端 HTTP Trigger 函数时，提供访问链接

- src/extension.ts
- src/lens/ServerlessLensProvider.ts
- src/tree/LocalResourceProvider.ts
> feat(Local Resource): 本地资源面板监听模版文件变化自动刷新

- src/services/FunService.ts
- src/utils/terminal.ts
多 template 情况下适配 Terminal 进行命令输出
针对 PowerShell 用 ${cmd1}; if ($?) {${cmd2}}
> fix(Multi Template): 多 template 情况下适配 Terminal 进行命令输出

- src/commands/deploy.ts
> fix(Local Resource Deploy): fix 本地资源面板点击 deploy 路径非绝对路径

- README.md
- package.json
- src/commands/localDebugFunction.ts
- src/commands/localInvokeConfig.ts
- src/commands/localInvokeFunction.ts
- src/commands/referRuntimeLib.ts
- src/commands/remoteInvokeFunction.ts
- src/extension.ts
- src/lens/ServerlessLensConfigItem.ts
- src/lens/ServerlessLensProvider.ts
- src/tree/LocalResourceProvider.ts
- src/utils/constants.ts
- src/utils/localConfig.ts
> feat(Local Invoke): support local invoke event config

- package.json
- src/commands/installPackage.ts
- src/extension.ts
- src/services/FunService.ts
- src/utils/constants.ts
> feat(Fun Install): 支持函数级别安装 Package

- package-lock.json
- package.json
- src/commands/startLocalSandbox.ts
- src/extension.ts
- src/services/FunService.ts
- src/utils/constants.ts
- src/utils/fun.ts
> feat(Local Sandbox): 集成 fun sandbox

- package.json
- src/commands/importFunction.ts
- src/commands/importService.ts
- src/utils/constants.ts
> feat(Fun Import): 允许配置导入的 Root Dir

- package-lock.json
- package.json
- src/utils/terminal.ts
> feat(Terminal Env): Add integrated fun path to created terminal

- package-lock.json
- package.json
- src/commands/localDebugFunction.ts
- src/services/FunService.ts
> perf(HTTP Trigger): 优化 HTTP Trigger 运行调试

- package.json
> perf(Extension Manifest): 优化命令顺序以及新增命令注册

- package-lock.json
- package.json
- resources/web/localInvoke/index.html
- src/commands/copyPasteFunction.ts
- src/commands/gotoFunctionCode.ts
- src/commands/gotoFunctionDefinition.ts
- src/commands/gotoNasDefinition.ts
- src/commands/gotoServiceDefinition.ts
- src/commands/gotoTemplate.ts
- src/commands/gotoTriggerDefinition.ts
- src/commands/localInvokeConfig.ts
- src/extension.ts
- src/extensionVariables.ts
- src/tree/LocalResourceProvider.ts
- src/utils/constants.ts
支持在本地资源树中复制函数定义并黏贴到某服务下，支持 Ctrl + C、Ctrl + V
> feat(Local Resource): Support copy & paste function definition

- src/completions/FunfileCompletionProvider.ts
- src/extension.ts
> feat(Funfile Completion): 提供关键字补全以及 fun-install 子命令补全

- src/schema/constants.ts
- src/schema/schema.ts
> perf(Template Completion): 提供 MemorySize 可选值自动补全

- package-lock.json
- package.json
- resources/web/localInvoke/index.html
- resources/web/localInvoke/style.css
- src/commands/switchEventFile.ts
- src/extension.ts
- src/utils/constants.ts
- src/utils/localConfig.ts
- src/webview/LocalInvokePanelCreator.ts
> feat(Invoke Panel): 支持配置 Quick Run/Debug 默认事件文件

- src/completions/FlowDefinitionCompletionProvider.ts
- src/decorations/RainbowDecorator.ts
- src/extension.ts
- src/language-service/schema/flowSchema.json
- src/language-service/services/jsonSchemaService.ts
- src/parser/ASTNode.ts
- src/utils/document.ts
__Function Flow__
1. 流程定义文件提供所有资源 key 字段的自动补全
2. 流程定义文件提供彩虹色空格渲染
> feat(Function Flow): flow definition file support auto-completion and rainbow-decoration

- package-lock.json
- package.json
- src/utils/terminal.ts
> feat(Fun): Disable fun version check

- src/extension.ts
- src/hovers/FlowDefinitionHoverProvider.ts
> feat(Function Flow): Support flow definition with hover tips

- src/commands/localDebugFunction.ts
> feat(Local Debug): Support auto check python & php debugger

- .gitignore
- .vscodeignore
- resources/web/flow/.env
- resources/web/flow/package-lock.json
- resources/web/flow/package.json
- resources/web/flow/public/index.html
- resources/web/flow/public/manifest.json
- resources/web/flow/scripts/build-non-split.js
- resources/web/flow/src/App.css
- resources/web/flow/src/App.tsx
- resources/web/flow/src/containers/FlowInfo/index.tsx
- resources/web/flow/src/declarations.d.ts
- resources/web/flow/src/index.css
- resources/web/flow/src/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/react-app-env.d.ts
- resources/web/flow/src/serviceWorker.ts
- resources/web/flow/src/services/service.ts
- resources/web/flow/tsconfig.json
- src/commands/fnf/showRemoteFlowInfo.ts
- src/descriptors/descriptor.ts
- src/extension.ts
- src/tree/fnf/FnFRemoteResourceProvider.ts
- src/utils/constants.ts
- src/webview/FlowInfoPanelCreator.ts
- tsconfig.json
提供 Function Flow 中流程远端信息面板，使用 React 架构的目的是为之后支持可视化做基础。
> feat(Function Flow): Support flow remote info panel

- resources/web/flow/package-lock.json
- resources/web/flow/package.json
- resources/web/flow/src/App.tsx
- resources/web/flow/src/components/IconButton/index.css
- resources/web/flow/src/components/IconButton/index.tsx
- resources/web/flow/src/components/TabPanel/index.tsx
- resources/web/flow/src/components/TableCell/index.tsx
- resources/web/flow/src/components/Tabs/index.tsx
- resources/web/flow/src/containers/ExecutionList/index.tsx
- resources/web/flow/src/containers/FlowInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
- src/services/FunctionFlowService.ts
- src/webview/FlowInfoPanelCreator.ts
> feat(Function Flow): Flow 资源面板提供流程定义与执行列表信息

- resources/web/flow/src/App.tsx
- resources/web/flow/src/containers/ExecutionList/index.tsx
- resources/web/flow/src/containers/ExecutionStart/index.tsx
- resources/web/flow/src/containers/FlowInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/props.d.ts
- src/services/FunctionFlowService.ts
- src/webview/FlowInfoPanelCreator.ts
> feat(Function Flow): Flow remote panel support start execution

- src/commands/fnf/createRemoteFlow.ts
- src/services/FunctionFlowService.ts
> feat(Function Flow): Support update flow definition and description

- package.json
- resources/web/flow/package-lock.json
- resources/web/flow/package.json
- resources/web/flow/src/App.tsx
- resources/web/flow/src/containers/FlowDefinition/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/utils/graph/constants.ts
- resources/web/flow/src/utils/graph/description.ts
- resources/web/flow/src/utils/graph/graph.ts
- resources/web/flow/src/utils/utils.ts
- src/commands/fnf/showDefinitionGraph.ts
- src/extension.ts
- src/utils/constants.ts
- src/webview/AbstractFlowPanelCreator.ts
- src/webview/AbstractInfoPanelCreator.ts
- src/webview/FlowDefinitionPanelCreator.ts
- src/webview/FlowInfoPanelCreator.ts
- src/webview/IInfoPanelCreator.ts
- src/webview/PanelManager.ts
> feat(Function Flow): 支持以图形化展示 flow 定义文件

- package.json
- resources/web/flow/src/containers/DefinitionGraph/index.tsx
- resources/web/flow/src/containers/ExecutionInfo/index.tsx
- resources/web/flow/src/containers/FlowDefinition/index.tsx
- resources/web/flow/src/containers/FlowDefinitionGraph/index.tsx
- resources/web/flow/src/containers/FlowInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/props.d.ts
> feat(Function Flow): 远端资源面板提供流程定义可视化以及执行使用流程定义可视化

- resources/web/flow/src/components/ReactJson/index.tsx
- resources/web/flow/src/containers/ExecutionHistory/index.tsx
- resources/web/flow/src/containers/ExecutionInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
> feat(Function Flow): 执行事件列表提供事件详情信息

- resources/web/flow/src/App.tsx
- resources/web/flow/src/containers/fc/FunctionInfo/index.css
- resources/web/flow/src/containers/fc/FunctionInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/routes/fc/index.tsx
- src/commands/remoteInvokeFunction.ts
- src/webview/FlowDefinitionPanelCreator.ts
- src/webview/FunctionInfoPanelCreator.ts
> feat(Remote Invoke): 远端函数信息面板复用本地函数事件配置信息

- src/commands/localDebugFunction.ts
VSCode Python Extension 所带的 Debugger 不像 VSCode 内置的 Nodejs Debugger，在 Python Debugger 被启动后，如果没有立刻 Attach 上，则会报错。
过去针对 Python Runtime 是在检测到 Image 存在后，wait 一段时间再启动 Debugger，但是这个效果在 windows 平台并不好。
现在改为检测到相应的 Image 以及 Port 的 Container 被启动后再启动 Debugger。
> perf(Local Debug): 优化 VSCode 调试模式启动时机

- src/commands/importFunction.ts
- src/commands/importService.ts
> feat(Fun Import): 支持选择 Import 目录

- src/commands/localDebugFunction.ts
- src/services/TemplateService.ts
> feat(Local Debug): Support Java Event Trigger Debug & Refactor Code

- resources/web/flow/src/containers/ExecutionHistory/index.tsx
- resources/web/flow/src/containers/fc/FunctionList/index.tsx
- resources/web/flow/src/containers/fc/ServiceInfo/index.tsx
- resources/web/flow/src/mocks/mock.ts
- resources/web/flow/src/routes/fc/index.tsx
- src/services/FunctionComputeService.ts
- src/webview/ServiceInfoPanelCreator.ts
> feat(Function Compute): 为远端服务提供新的 Webview，提供函数列表

- resources/web/flow/src/containers/fc/FunctionInfo/index.tsx
- resources/web/flow/src/containers/fc/TriggerList/index.tsx
- resources/web/flow/src/mocks/mock.ts
- src/services/FunctionComputeService.ts
- src/tree/RemoteResourceExplorer.ts
- src/webview/FunctionInfoPanelCreator.ts
- src/webview/ServiceInfoPanelCreator.ts
> feat(Function Compute): 远端函数面板提供触发器列表 & 支持跳转到触发器面板

- templates/fun.sh
> fix(Fun Posix Script): fix posix platform random tip unexpected operator

- package.json
- src/extension.ts
- src/language-service/model/customTags.ts
- src/language-service/schema/rosSchema.ts
- src/utils/document.ts
1. 语法支持从 template 文件拓展为 yml 文件
2. Aliyun::Serverless::Service 下的 NasConfig 支持 Auto 配置
3. ROS Function 支持 Fn::Sub
> perf(Template): perf grammar tip

- src/commands/switchRegion.ts
> fix(commands/switchregion): error when switching Region

- CHANGELOG.md
- package-lock.json
- package.json
- src/commands/createFunction.ts
- src/language-service/schema/ros/ALIYUN-FC-Function.json
- src/language-service/schema/ros/ALIYUN-FC-Service.json
- src/language-service/schema/rosSchema.ts
- src/schema/constants.ts
- src/schema/schema.ts
- src/services/FunService.ts
- src/utils/file.ts
- src/utils/fun.ts
- src/utils/runtime.ts
1. Service schema 中增加 TracingConfig 字段
2. Function schema 中增加 InstanceLifecycleConfig 字段
3. Function ros schema 中增加 InstanceType、CustomContainerConfig、CAPort 以及 AsyncConfiguration 字段
> update service and function schema

- CHANGELOG.md
- package-lock.json
- package.json
update fun version from 3.6.20 to 3.6.24
> build: fix vscode extension unavailable in macos monterey
